//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplication2.ServiceReference1.HelloWorldResponse HelloWorld(WebApplication2.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebApplication2.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSquare", ReplyAction="*")]
        int GetSquare(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSquare", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetSquareAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBAMtoHRK", ReplyAction="*")]
        float GetBAMtoHRK(float a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBAMtoHRK", ReplyAction="*")]
        System.Threading.Tasks.Task<float> GetBAMtoHRKAsync(float a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHRKtoBAM", ReplyAction="*")]
        float GetHRKtoBAM(float a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHRKtoBAM", ReplyAction="*")]
        System.Threading.Tasks.Task<float> GetHRKtoBAMAsync(float a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBAMtoRSD", ReplyAction="*")]
        float GetBAMtoRSD(float a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBAMtoRSD", ReplyAction="*")]
        System.Threading.Tasks.Task<float> GetBAMtoRSDAsync(float a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRSDtoBAM", ReplyAction="*")]
        float GetRSDtoBAM(float a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRSDtoBAM", ReplyAction="*")]
        System.Threading.Tasks.Task<float> GetRSDtoBAMAsync(float a);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplication2.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplication2.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication2.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication2.ServiceReference1.WebService1Soap>, WebApplication2.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.HelloWorldResponse WebApplication2.ServiceReference1.WebService1Soap.HelloWorld(WebApplication2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplication2.ServiceReference1.HelloWorldRequest inValue = new WebApplication2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplication2.ServiceReference1.HelloWorldRequestBody();
            WebApplication2.ServiceReference1.HelloWorldResponse retVal = ((WebApplication2.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.HelloWorldResponse> WebApplication2.ServiceReference1.WebService1Soap.HelloWorldAsync(WebApplication2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebApplication2.ServiceReference1.HelloWorldRequest inValue = new WebApplication2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplication2.ServiceReference1.HelloWorldRequestBody();
            return ((WebApplication2.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int GetSquare(int a) {
            return base.Channel.GetSquare(a);
        }
        
        public System.Threading.Tasks.Task<int> GetSquareAsync(int a) {
            return base.Channel.GetSquareAsync(a);
        }
        
        public float GetBAMtoHRK(float a) {
            return base.Channel.GetBAMtoHRK(a);
        }
        
        public System.Threading.Tasks.Task<float> GetBAMtoHRKAsync(float a) {
            return base.Channel.GetBAMtoHRKAsync(a);
        }
        
        public float GetHRKtoBAM(float a) {
            return base.Channel.GetHRKtoBAM(a);
        }
        
        public System.Threading.Tasks.Task<float> GetHRKtoBAMAsync(float a) {
            return base.Channel.GetHRKtoBAMAsync(a);
        }
        
        public float GetBAMtoRSD(float a) {
            return base.Channel.GetBAMtoRSD(a);
        }
        
        public System.Threading.Tasks.Task<float> GetBAMtoRSDAsync(float a) {
            return base.Channel.GetBAMtoRSDAsync(a);
        }
        
        public float GetRSDtoBAM(float a) {
            return base.Channel.GetRSDtoBAM(a);
        }
        
        public System.Threading.Tasks.Task<float> GetRSDtoBAMAsync(float a) {
            return base.Channel.GetRSDtoBAMAsync(a);
        }
    }
}
