//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplication3.ServiceReference1.HelloWorldResponse HelloWorld(WebApplication3.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebApplication3.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetDispatcherInfoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDispatcherInfo", ReplyAction="*")]
        WebApplication3.ServiceReference1.GetDispatcherInfoResponse GetDispatcherInfo(WebApplication3.ServiceReference1.GetDispatcherInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDispatcherInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference1.GetDispatcherInfoResponse> GetDispatcherInfoAsync(WebApplication3.ServiceReference1.GetDispatcherInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication3.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplication3.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication3.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplication3.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDispatcherInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDispatcherInfo", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication3.ServiceReference1.GetDispatcherInfoRequestBody Body;
        
        public GetDispatcherInfoRequest() {
        }
        
        public GetDispatcherInfoRequest(WebApplication3.ServiceReference1.GetDispatcherInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDispatcherInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetDispatcherInfoRequestBody() {
        }
        
        public GetDispatcherInfoRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDispatcherInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDispatcherInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication3.ServiceReference1.GetDispatcherInfoResponseBody Body;
        
        public GetDispatcherInfoResponse() {
        }
        
        public GetDispatcherInfoResponse(WebApplication3.ServiceReference1.GetDispatcherInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDispatcherInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDispatcherInfoResult;
        
        public GetDispatcherInfoResponseBody() {
        }
        
        public GetDispatcherInfoResponseBody(string GetDispatcherInfoResult) {
            this.GetDispatcherInfoResult = GetDispatcherInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication3.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication3.ServiceReference1.WebService1Soap>, WebApplication3.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication3.ServiceReference1.HelloWorldResponse WebApplication3.ServiceReference1.WebService1Soap.HelloWorld(WebApplication3.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplication3.ServiceReference1.HelloWorldRequest inValue = new WebApplication3.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplication3.ServiceReference1.HelloWorldRequestBody();
            WebApplication3.ServiceReference1.HelloWorldResponse retVal = ((WebApplication3.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference1.HelloWorldResponse> WebApplication3.ServiceReference1.WebService1Soap.HelloWorldAsync(WebApplication3.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication3.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebApplication3.ServiceReference1.HelloWorldRequest inValue = new WebApplication3.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplication3.ServiceReference1.HelloWorldRequestBody();
            return ((WebApplication3.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication3.ServiceReference1.GetDispatcherInfoResponse WebApplication3.ServiceReference1.WebService1Soap.GetDispatcherInfo(WebApplication3.ServiceReference1.GetDispatcherInfoRequest request) {
            return base.Channel.GetDispatcherInfo(request);
        }
        
        public string GetDispatcherInfo(int id) {
            WebApplication3.ServiceReference1.GetDispatcherInfoRequest inValue = new WebApplication3.ServiceReference1.GetDispatcherInfoRequest();
            inValue.Body = new WebApplication3.ServiceReference1.GetDispatcherInfoRequestBody();
            inValue.Body.id = id;
            WebApplication3.ServiceReference1.GetDispatcherInfoResponse retVal = ((WebApplication3.ServiceReference1.WebService1Soap)(this)).GetDispatcherInfo(inValue);
            return retVal.Body.GetDispatcherInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference1.GetDispatcherInfoResponse> WebApplication3.ServiceReference1.WebService1Soap.GetDispatcherInfoAsync(WebApplication3.ServiceReference1.GetDispatcherInfoRequest request) {
            return base.Channel.GetDispatcherInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication3.ServiceReference1.GetDispatcherInfoResponse> GetDispatcherInfoAsync(int id) {
            WebApplication3.ServiceReference1.GetDispatcherInfoRequest inValue = new WebApplication3.ServiceReference1.GetDispatcherInfoRequest();
            inValue.Body = new WebApplication3.ServiceReference1.GetDispatcherInfoRequestBody();
            inValue.Body.id = id;
            return ((WebApplication3.ServiceReference1.WebService1Soap)(this)).GetDispatcherInfoAsync(inValue);
        }
    }
}
